language: android
android:
  components:
    # The BuildTools version 
    - build-tools-19.1.0

    # The SDK version used to compile 
    - android-22

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    #- addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-17
notifications:
  email:
    - oussama.abdellah@gmail.com